info:
  name: OpenID Configuration JWKS
  type: http
  seq: 2

http:
  method: GET
  url: "{{HostUri}}/.well-known/openid-configuration/jwks"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
